[cjson]
type = "service_account"
project_id = "sever-416401"
private_key_id = "0ceb71f7b2ad10b43fcc3d9f7135fc170604d34c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCq1iZI+FJyXxwX
m6US9QI2r3e7IEJymdAAQl1bysVsG88E+Ulx0mjltWAZX7yQAdaV21LJlw7KLhbv
SxSoWDqNrnCRyrc4wJGzWedATcBwPlza6/iFZvVBIyh5IKz++tvERUpkIlo9NxCf
ymLCvnODLEMbhXcB50JgwWYjnqcHCwdPxhI3QyKwmF8LrwfKpFze/aizwjD45lbO
+Y9WUpeo2NrDWmn3s3gUWnqVUZB64fibiaKetJ+l6ubgAOBczQxs6C1fvXmgooNd
n6ipVsuV1XAAt5SrZBs21dTrRUhoMtJeoM5rUw/7tMf6NPGs0Sk0U+iYkZOtPK6g
iOOYWzgnAgMBAAECggEAA0sGfBo0gkAWfnDOVH7rKhrlL9lWC14Vdg1rCq87CzO/
OiU3oIPB6HxzDxPBddsuaj9K9lgJlz8ey3UPv5QxaMEnw7+vGxJ0AvHxzoad9evv
bHu0LWO7LyRadHjhrNAw6hsioHe2QP86b4IX6xFMKiEK/oRRM3TkQPfPz4VdSq1V
KZd2UndVw1cM2ifHN1CFG7EOnv0zLqaaOk7EBvDpbXmrcqPdSxQB+45GYnJOHJKD
pcJbpC72783vJASvzRxDomwGw3wuOOUfeaKtBDkCF4tFqXMlzkaVJ59C/U53mJm2
CWndJy54OFUcxc50WU0lHCp6Fr0KjXoAN9nMpLQ5RQKBgQDg6sM36ESz2AKwAiq3
D+Vwx2EtMcwIvKG90ADd30NeM5aCjjIoWxZaeeLUhuqTZP/Pasuqr1FEQAqnvXrp
LYIj/a8PD/a37Y4ugiYqvzqf+Oz1BqfGUND4VMQhphSEKpls31fWuZ9ZZOJWSBi0
wqfTX0oqeouxDRvLmOcKU/UPOwKBgQDCchjRCsCKJbAhXiKBQ5/aMklGOSW5N4JJ
amogT1VYdxVfipbkoVCa8i4kPP4B31jDq9Or6j1goeesrGq57RNaqujf1Y2MfX3A
u6tfS5jVeowIdVP8BmYaRQ6ttDpUsRWhQHxN1C/5YVFHIv9pKSop7/Op4+s9SOZS
5ibita8EBQKBgA7GPRaiEklCCkMnkUi/KZIz9qUyXTXBtloynKv2a4V3nA5taswN
17UPxp+xUR1niApG+KP4qjzyfACyyK0iiSb2FhbGNK22VB2n/PvX3fD+OAqMal7z
lhaJ8uxG7ZgU+EkXjryTKu2DW/7Q85aEJuQSoVuS+zQhKU9BdwPNqg5bAoGBAL/G
gl1iSmW2KBGw4z00citk30oIQQF9Et3Pu53kQNuAj67sZEhYJcS8SO/qy+cS3lwW
Uy1CWIi/Bl0SrCx1+1m4KPfiirneZzG4ppvVVoZuWEBbX5q4wOj15TVDBSjUgu3I
SREFzs8ZwWz0wo14USKNi3eq2C9Yf/mRDxcYc+X1AoGANBcujiU9QdwgvdsdQ5Ve
RRXOY8ZKReoQjPCYe02YQZu3CgHGf/LeVIQrN9Btclvsiw7CSnlmsFbzNNHYjh5r
8Ks+TGq5EZPd/DYZLtG5D0MCtlbOwOVWIAuyhRjTQMnZFn44Fcffb5z9VDc7HaVV
lDHYdyjs4bISEv6VJBwWHBU=
-----END PRIVATE KEY-----
"""
client_email = "demo-511@sever-416401.iam.gserviceaccount.com"
client_id = "101608156569868501121"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/demo-511%40sever-416401.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
